services:
    php:
        image: abourtnik/laravel
        container_name: php_container
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        networks:
            - application
        restart: unless-stopped
    nginx:
        image: nginx:1.22.0-alpine
        container_name: nginx_container
        networks:
            - application
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        links:
            - php
        restart: unless-stopped
    bun:
        image: oven/bun:1.2.0
        container_name: bun_container
        ports:
            - "5173:5173"
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_IGNORE_INITIAL=true
        #command: tail -f /dev/null
        command: bun run dev
        networks:
            - application
    reverb:
        container_name: reverb_container
        image: clipzone/php
        working_dir: /var/www/html
        command: php artisan reverb:start --port=6001 --debug
        ports:
            - "6001:6001"
        volumes:
            - ./:/var/www/html
        networks:
            - application
        depends_on:
            - php
        restart: unless-stopped
networks:
    application:
        driver: bridge
